CREATE DATABASE IF NOT EXISTS cofre_pedro CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cofre_pedro;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  senha_hash VARCHAR(255) NOT NULL,
  sal_criptografia VARBINARY(16) NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS credenciais (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id INT UNSIGNED NOT NULL,
  servico VARCHAR(120) NOT NULL,
  usuario_servico VARCHAR(190) NOT NULL,
  senha_cifrada TEXT NOT NULL,
  nonce VARBINARY(12) NOT NULL,
  etiqueta VARBINARY(16) NOT NULL,
  observacoes VARCHAR(500) DEFAULT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_usuario_servico (usuario_id, servico),
  CONSTRAINT fk_credenciais_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB;
